src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SortieRepository::class)
 */
class Sortie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateHeureDebut;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="date")
     */
    private $dateLimiteInscription;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbInscriptionMax;

    /**
     * @ORM\Column(type="text")
     */
    private $infosSortie;


    /**
     * @ORM\ManyToOne(targetEntity=Lieu::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=true)
     */
    private $lieu;

    /**
     * @ORM\ManyToOne(targetEntity=Etat::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity=Campus::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $campus;

    /**
     * @ORM\ManyToOne(targetEntity=Participant::class, inversedBy="sortiesOrganisees")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organisateur;

    /**
     * @ORM\ManyToMany(targetEntity=Participant::class, inversedBy="sorties")
     */
    private $participants;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $modif_annulation;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateHeureDebut(): ?\DateTimeInterface
    {
        return $this->dateHeureDebut;
    }

    public function setDateHeureDebut(?\DateTimeInterface $dateHeureDebut): self
    {
        $this->dateHeureDebut = $dateHeureDebut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateLimiteInscription(): ?\DateTimeInterface
    {
        return $this->dateLimiteInscription;
    }

    public function setDateLimiteInscription(\DateTimeInterface $dateLimiteInscription): self
    {
        $this->dateLimiteInscription = $dateLimiteInscription;

        return $this;
    }

    public function getNbInscriptionMax(): ?int
    {
        return $this->nbInscriptionMax;
    }

    public function setNbInscriptionMax(int $nbInscriptionMax): self
    {
        $this->nbInscriptionMax = $nbInscriptionMax;

        return $this;
    }

    public function getInfosSortie(): ?string
    {
        return $this->infosSortie;
    }

    public function setInfosSortie(string $infosSortie): self
    {
        $this->infosSortie = $infosSortie;

        return $this;
    }


    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): self
    {
        $this->campus = $campus;

        return $this;
    }

    public function getOrganisateur(): ?Participant
    {
        return $this->organisateur;
    }

    public function setOrganisateur(?Participant $organisateur): self
    {
        $this->organisateur = $organisateur;

        return $this;
    }

    /**
     * @return Collection<int, Participant>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        $this->participants->removeElement($participant);

        return $this;
    }

    public function getModifAnnulation(): ?string
    {
        return $this->modif_annulation;
    }

    public function setModifAnnulation(?string $modif_annulation): self
    {
        $this->modif_annulation = $modif_annulation;

        return $this;
    }
}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\Etat;
use App\Entity\Lieu;
use App\Entity\Sortie;
use App\Entity\Ville;
use App\Form\LieuModalFormType;
use App\Form\LieuType;
use App\Form\SortieType;
use App\Form\VilleFormType;
use App\Form\LieuFormType;
use App\Repository\EtatRepository;
use App\Repository\LieuRepository;
use App\Repository\SortieRepository;
use App\Repository\VilleRepository;
use Detection\MobileDetect;
use Doctrine\DBAL\Types\TextType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

/**
 * @Route("/sortie", name="sortie_")
 */
class SortieController extends AbstractController
{
    private $authorizationChecker;

    public function __construct(AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }
    /**
     * @Route("", name="home")
     */
    public function index(): Response
    {
        return $this->render('sortie/index.html.twig', [
            'controller_name' => 'SortieController',
        ]);
    }

    /**
     * @Route("/create", name="create")
     */

    public function create( Request  $request,
                            EntityManagerInterface $entityManager,
                            VilleRepository $villeRepository,
                            LieuRepository $lieuRepository,
                            EtatRepository $etatRepo) : Response
    {

        //récuperation de l'utilisateur
        $userCo = $this->getUser();

        //si utilisateur plus connecter redirection a la page de connection
        if($userCo === null){
            return $this->redirectToRoute('app_login');
        }

        $campus = $userCo->getCampus();
        $ville = $listeVille = $villeRepository->findAll();
        $lieu = $lieuRepository->findAll();

        //on initialise notre variable erreur
        $error = "";
        $sortie = new Sortie();
        $newLieu =  new Lieu();
        $lieuModal =  new Lieu();
        //Formulaire ajout de sortie
        $sortieForm = $this->createForm(SortieType ::class, $sortie);
        $lieuForm = $this->createForm(LieuType::class, $newLieu);
        $lieuModalForm = $this->createForm(LieuFormType::class, $lieuModal);


        //récupération des données du formulaire
        $sortieForm->handleRequest($request);
        $lieuForm->handleRequest($request);
        $lieuModalForm->handleRequest($request);

          if ($sortieForm->isSubmitted() && $sortieForm->isValid() ) {

            // Si utilisateur souhaite Enregister sa Sortie
            if($sortieForm->getClickedButton() && 'enregistrer'=== $sortieForm->getClickedButton()->getName()) {
                $etat = $etatRepo->find(1);
            }
            if($sortieForm->getClickedButton() && 'publier'=== $sortieForm->getClickedButton()->getName()) {
                $etat = $etatRepo->find(2);
            }
                $dateDebut = $sortieForm->get('dateHeureDebut');
                $dateFin = $sortieForm -> get('dateLimiteInscription');

                //Gestion des erreurs de date
                if ($dateFin->getData() > $dateDebut->getData()) {
                    $error = [
                        'Key' => -1,
                        'value' => "La date de limite d'inscription ne peut pas etre aprés la date de la sortie"
                    ];
                }

                if ($error == "") {
                    //On enregistrer la sortie
                    $sortie->setOrganisateur($userCo);
                    $sortie->setEtat($etat);
                    $sortie->setCampus($campus);
                    $em = $this->getDoctrine()->getManager();
                    $em->persist($sortie);
                    $em->flush();
                    $this->addFlash('success', "La sortie a été créée avec succès");
                    return $this->redirectToRoute('main_home');
                }
            }


        if ($lieuModalForm->isSubmitted() && $lieuModalForm->isValid()) {
            // Récupérer les données du formulaire
            $lieuModal = $lieuModalForm->getData();

            // Enregistrer le lieu dans la base de données
            $entityManager->persist($lieuModal);
            $entityManager->flush();

            // Redirection ou autre traitement après l'enregistrement réussi

            // Exemple de redirection
            return $this->redirectToRoute('sortie_create');
        }


        return $this->render('sortie/create.html.twig', [
            'sortieForm' => $sortieForm->createView(),
            'sortie' => $sortie,
            'listeVille' => $listeVille,
            'userCo' => $userCo,
            'campus' => $campus,
            'error' => $error,
            "lieu" => $lieu,
            "lieuForm" => $lieuForm->createView(),
            "ville" => $ville,
            'lieuModalForm' => $lieuModalForm->createView()

        ]);
    }

    /**
     * @Route("/modif/{id}", name="modif", requirements={"id"="\d+"})
     */
    public function modifier(int $id, Request $request,
                             EtatRepository $etatRepository,
                             VilleRepository $villeRepository,
                             LieuRepository $lieuRepository,
                            SortieRepository $sortieRepository): Response
    {
        $userCo =  $this->getUser();
        $sortie = $sortieRepository->find($id);
        $userOrganisateur = $sortie->getOrganisateur();

        if($userCo != $userOrganisateur){
            $this->addFlash('danger', "Redirection vous n'avez pas accés a cette page");
            return $this->redirectToRoute('main_home');
        }

        $campus = $sortie->getOrganisateur()->getCampus();
        $lieuSortie = $sortie->getLieu();
        $latitude = $lieuSortie->getLatitude();
        $longitude = $lieuSortie->getLongitude();
        $villeSortie= $lieuSortie->getVille();

        $ville = $villeRepository->findAll();
        $lieu = $lieuRepository->findAll();

        $error = "";
        $lieuForm = $this->createForm(LieuType::class);
        $lieuModalForm = $this->createForm(LieuModalFormType::class);
        $sortieForm = $this->createForm(SortieType::class, $sortie);
        $sortieForm->handleRequest($request);

        if ($sortieForm->isSubmitted() && $sortieForm->isValid()) {

            //Recuperation du choix si Modification simple ou Si Publication
            if ($sortieForm->getClickedButton() && 'enregistrer' === $sortieForm->getClickedButton()->getName()) {
                $etat = $etatRepository->find(1);
            }
            if ($sortieForm->getClickedButton() && 'publier' === $sortieForm->getClickedButton()->getName()) {
                $etat = $etatRepository-> find(2);
            }

            $dateDebut = $sortieForm->get('dateHeureDebut');
            $dateFin = $sortieForm -> get('dateLimiteInscription');

            //Gestion des erreurs de date
            if ($dateFin->getData() > $dateDebut->getData()) {
                $error = [
                    'Key' => -1,
                    'value' => "La date de limite d'inscription ne peut pas etre aprés la date de la sortie"
                ];
            }
            if ($error == "") {
                $sortie->setEtat($etat);
                $em = $this->getDoctrine()->getManager();
                $em->persist($sortie);
                $em->flush();
                $this->addFlash('success', "La sortie a été modifiée avec succès");
                return $this->redirectToRoute('main_home');
            }
        }

        return $this->render('sortie/create.html.twig', [
            'sortie' => $sortie,
            'campus'=> $campus,
            'latitude'=> $latitude,
            'longitude'=>$longitude,
            'lieu'=>$lieu,
            'ville' =>$ville,
            'lieuSortie'=>$lieu,
            'villeSortie' =>$villeSortie,
            'sortieForm' => $sortieForm->createView(),
            'error' => $error,
            "lieuForm" => $lieuForm->createView(),
            'lieuModalForm' => $lieuModalForm->createView(),
        ]);

    }
    /**
     * @Route("/detail/{id}", name="detail")
     */
    public function detail(int $id, SortieRepository $sortieRepository): Response
    {
        $mobileDetect = new MobileDetect();

        $sortie = $sortieRepository->find($id);
        $organisateur = $sortie->getOrganisateur();
        $campus = $sortie->getCampus();
        $dateSortie = $sortie->getDateHeureDebut()->format('d-m-Y H:i');
        $dateLimiteSortie = $sortie->getDateLimiteInscription()->format('d-m-Y');
        $lieu = $sortie->getLieu();
        $participants = $sortie->getParticipants()->count();

        if ($mobileDetect->isMobile()) {
            return $this->render('mobile/mobiledetailssortie.html.twig', [
                'sortie' => $sortie,
                'campus' => $campus,
                'dateLimite'=> $dateLimiteSortie,
                'dateSortie' => $dateSortie,
                'lieu' => $lieu,
                'participants' => $participants,
                'organisateur' => $organisateur,
            ]);
        }else {

            return $this->render('sortie/detail.html.twig', [
                'sortie' => $sortie,
                'campus' => $campus,
                'dateLimite' => $dateLimiteSortie,
                'dateSortie' => $dateSortie,
                'lieu' => $lieu,
                'participants' => $participants,
                'organisateur' => $organisateur,

            ]);
        }
    }

    /**
     * @Route("/annulation/{id}", name="annulation")
     */
    public function annulation(int $id, SortieRepository $sortieRepository): Response
    {

templates/sortie/annulation.html.twig
{% extends 'base.html.twig' %}

{%  block title %} Annuler : {{ sortie.nom |upper }} |  {{ parent() }}{%  endblock %}

{% block body %}

    <h2 class="text-center">Annulation de la sortie : {{ sortie.nom }}</h2>
    <br>
    <div class="card-body px-4 py-5 px-md-5" align="center">

            <div class="col-md-6 mb-4">
                <label for="nom">Nom : </label> {{ sortie.nom | capitalize}}
            </div>
            <div class="col-md-6 mb-4">
                <label for="nom" >Campus  : </label> {{ campus.nom |capitalize}}
            </div>

            <div class="col-md-6 mb-4">
                <label for="dateSortie">Date et heur de la sortie : </label> {{ dateSortie }}
            </div>
            <div class="col-md-6 mb-4">
                <label for="lieu">Lieu : </label> {{ lieu.nom |capitalize}}
            </div>

            <div class="col-md-6 mb-4">
                <label for="dateLimit">Rue : </label> {{ lieu.rue }} , {{ lieu.ville}}
            </div>
        <form action="{{ path('sortie_confirm_annulation', {'id': sortie.id}) }}" method="POST">
            <label for="motif">Motif d'annulation :</label>
            <textarea id="motif" name="motif" class="form-control form-control-m" required> {{ sortie ? sortie.modifAnnulation : ""  }}</textarea>
            <button type="submit" class="btn btn-danger"> Annuler la sortie </button>


    </div>


{% endblock %}

templates/sortie/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% if sortie.etat != null %}
        <h1 class="text-center">Modification de la sortie</h1>
    {% else %}
        <h1 class="text-center">Organiser une nouvelle sortie !</h1>
    {% endif %}

    {% if error %}
        <div class="alert alert-danger">{{ error.value }}</div>
    {% endif %}
    {{ form_start(sortieForm ,{'attr': {'id': 'form_sortie'} }) }}
    <div class="card-body px-4 py-5 px-md-5">
        <div class="row">
            <div class="col-md-6 mb-4">
                <div class="form-outline mb-4">
                    {{ form_row(sortieForm.nom) }}
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="form-outline mb-4">
                    {{ form_row(sortieForm.dateHeureDebut) }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-4">
                <div class="form-outline mb-4">
                    {{ form_row(sortieForm.duree) }}
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="form-outline mb-4">
                    {{ form_row(sortieForm.dateLimiteInscription) }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-4">
                <div class="form-outline mb-4">
                    {{ form_row(sortieForm.nbInscriptionMax) }}
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="form-outline mb-4">
                    {{ form_row(sortieForm.infosSortie) }}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-4">
            <div class="form-outline mb-4">
                Campus :
                {% if sortie.etat != null %}
                    {{ form_widget(sortieForm.campus) }}
                    {{ form_row(sortieForm.lieu) }}

                {% else %}
                    <input type="text" class="form-control form-control-m" value="{{ campus.nom }}" readonly>
                    {{ form_widget(sortieForm.campus,{'attr': {'class': 'd-none'} }) }}
                    {{ form_widget(sortieForm.lieu,{'attr': {'class': 'd-none'} }) }}

                {% endif %}
                <br>
                {{ form_widget(sortieForm.enregistrer) }}
                {{ form_widget(sortieForm.publier) }}

                <button class="btn btn-danger" onclick="window.location.href ='{{ path('main_home') }}'">Annuler</button>
                {{ form_end(sortieForm) }}
            </div>
        </div>
        {% if sortie.etat == null %}

            <div class="col-md-6 mb-4">
                <div class="form-outline mb-4">
                    {{ include('admin/addlieu.html.twig') }}
                    <button type="button" class="btn btn-primary"  id="btnAjouterLieu" data-toggle="modal" data-target="#addLieuModal">
                        Ajouter un lieu
                    </button>
                </div>
            </div>
        {% endif %}
    </div>

    <div class="col-8">
    </div>



    <!-- Modal -->
    <div class="modal fade" id="addLieuModal" tabindex="-1" aria-labelledby="addLieuModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addLieuModalLabel">Ajouter un nouveau lieu</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ form_start(lieuModalForm, {'attr': {'id': 'form_lieu_modal'}}) }}
                  {{ form(lieuModalForm) }}

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" id="btnFermer" data-dismiss="modal">Fermer</button>
                    <button type="submit" class="btn btn-primary" id="enregistrerLieuBtn">Enregistrer</button>
                </div>
                {{ form_end(lieuModalForm) }}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#addLieuModal').modal('hide');


            $('#btnAjouterLieu').click(function() {
                $('#addLieuModal').modal('show');
            });

            $('#btnFermer').click(function() {
                $('#addLieuModal').modal('hide');
            });

            // Envoyer le formulaire lorsque le bouton "Enregistrer" du modal est cliqué
            $('#addLieuModal').on('click', '#enregistrerLieuBtn', function() {
                $('#form_lieu_modal').submit();
            });

            // Fermer le modal après l'envoi du formulaire
            $('#form_lieu_modal').on('submit', function() {
                $('#addLieuModal').modal('hide');
            });
        });


    </script>


{% endblock %}

{% block title %}
    {% if sortie.nom != null %}
        Modifier votre sortie |  {{ parent() }}
    {% else %}
        Organiser une sortie |  {{ parent() }}
    {% endif %}
{% endblock %}

templates/sortie/detail.html.twig
{% extends 'base.html.twig' %}

{%  block title %} {{ sortie.nom |upper }} |  {{ parent() }}{%  endblock %}

{% block body %}

        <h2 class="text-center">Détail de la sortie : {{ sortie.nom }}</h2>
        <br>
    <div class="card-body px-4 py-5 px-md-5" align="center">
        <div class="row">
            <div class="col-md-6 mb-4">
                <label for="nom">Nom : </label> {{ sortie.nom | capitalize}}
            </div>
            <div class="col-md-6 mb-4">
                <label for="nom" >Campus  : </label> {{ campus.nom |capitalize}}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-4">
                <label for="dateSortie">Date et heur de la sortie : </label> {{ dateSortie }}
            </div>
            <div class="col-md-6 mb-4">
                <label for="lieu">Lieu : </label> {{ lieu.nom |capitalize}}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 mb-4">
                <label for="dateLimit">Date limite d'inscription : </label> {{ dateLimite }}
            </div>
            <div class="col-md-6 mb-4">
                <label for="dateLimit">Rue : </label> {{ lieu.rue }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-4">
                <label for="nbPlace">Nombre d'inscrits :</label> {{ participants }} / {{ sortie.nbInscriptionMax }}
            </div>

            <div class="col-md-6 mb-4">
                <label for="nbPlace">Ville :</label> {{ lieu.ville}}
            </div>
        </div>
        <div class="row">

            <div class="col-md-6 mb-4">
                <label for="duree">Durée : </label> {{ sortie.duree }} minutes
            </div>
            <div class="col-md-6 mb-4">
                <label for="duree">Longitude : </label> {{ lieu.longitude}}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 mb-4">
                <label for="description">Description : </label> {{ sortie.infosSortie}}
            </div>
            <div class="col-md-6 mb-4">
                <label for="description">Latitude : </label> {{ lieu.latitude}}
            </div>
        </div>
    </div>
    <div class="container">
        {% if participants !=0 %}
        <h3 class="text-center">Liste des participants</h3>

        <table class="table">
            <thead  class="thead-dark">
                <tr>
                    <th scope="col">Pseudo</th>
                    <th scope="col">Nom </th>
                </tr>
                {% for participant in sortie.participants %}
                    <tr>
                        <td>{{ participant.pseudo }}</td>
                        <td>{{ participant.nom |capitalize}} {{ participant.prenom |capitalize}} </td>
                    </tr>
                 {% endfor %}
            </thead>
        </table>
        {% else %}
            <div class="alert-success">
                <h5> Il n'y a aucun participant pour le moment</h5></div>
        {% endif %}
    </div>

{% endblock %}

templates/sortie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SortieController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/GoOutENI/src/Controller/SortieController.php'|file_link(0) }}">src/Controller/SortieController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/GoOutENI/templates/sortie/index.html.twig'|file_link(0) }}">templates/sortie/index.html.twig</a></code></li>
    </ul>
</div>


{% endblock %}

templates/sortie/test.html.twig
<div
        {{ attributes }}
>
    {{ form_start(form) }}
    {{ form_row(form.meal) }}
    {{ form_row(form.mainFood) }}
    {{ form_end(form) }}
</div>